version: '3.6'

services:
  astroport:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/astroport
      - IPFS_VERSION=${IPFS_VERSION:-0.20.0}
      context: ../
      dockerfile: docker/astroport/Dockerfile
    restart: unless-stopped
    ports:
    - 1234
    - 12345
    tty: true
    volumes:
    - home:/home:delegated
    - home:/home/zen/.zen/game/players:delegated
    working_dir: /home/zen

volumes:
  home:
