version: '3.6'

services:
  astroport:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/astroport
      - IPFS_VERSION=${IPFS_VERSION:-0.16.0}
      context: ../
      dockerfile: docker/astroport/Dockerfile
    network_mode: host
    restart: unless-stopped
    tty: true
    volumes:
    - data:/home/zen/Astroport:cached
    - ipfs:/home/zen/.ipfs:cached,ro
    - zen:/home/zen/.zen:delegated
    working_dir: /home/zen

volumes:
  data:
  ipfs:
  zen:
