version: '3.6'

services:
  docker:
    environment:
    - ENV=${ENV}
    - SHELL=${DOCKER_SHELL}
    image: ${DOCKER_REPOSITORY}/docker:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_1234_CHECK_HTTP=/
    - SERVICE_1234_NAME=${COMPOSE_SERVICE_NAME}-docker-1234
    - SERVICE_1234_TAGS=${DOCKER_SERVICE_1234_TAGS}

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK_PRIVATE}
  public:
    external: true
    name: ${DOCKER_NETWORK_PUBLIC}
