version: '3.6'

services:
  astroport:
    build:
      args:
      - DOCKER_REPOSITORY=${DOCKER_REPOSITORY}
      - GID=${HOST_GID}
      - UID=${HOST_UID}
    container_name: ${COMPOSE_PROJECT_NAME}-astroport
    domainname: ${DOMAINNAME:-localhost}
    hostname: ${HOSTNAME:-astroport}
    image: ${DOCKER_REPOSITORY}/astroport:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_1234_CHECK_HTTP=/test
    - SERVICE_1234_NAME=${COMPOSE_SERVICE_NAME}-astroport-1234
    - SERVICE_1234_TAGS=${HOST_ASTROPORT_SERVICE_1234_TAGS:-}
