version: '3'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "8081:80"
    volumes:
      - /home/sc/Documents/nextcloud:/var/www/html/data
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=nc       # Ajout de ces lignes
      - NEXTCLOUD_ADMIN_PASSWORD=nc   # Ajout de ces lignes
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: nextcloud_db
    volumes:
      - /chemin/vers/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud

  web:
    image: nginx:latest
    container_name: nextcloud_web
    ports:
      - "8443:443"
    volumes:
      - ~/Documents/maxence/github/astroport/astroport-maxence/adventure/infra/maxence.lancosme@ynov.com/nextcloud/data:/var/www/html/data
      - ~/Documents/maxence/github/astroport/astroport-maxence/adventure/infra/maxence.lancosme@ynov.com/nextcloud/config:/var/www/html/config
      - ~/Documents/maxence/github/astroport/astroport-maxence/adventure/infra/maxence.lancosme@ynov.com/nextcloud/apps:/var/www/html/apps
      - ~/Documents/maxence/github/astroport/astroport-maxence/adventure/infra/maxence.lancosme@ynov.com/nextcloud/themes:/var/www/html/themes
      - ~/Documents/maxence/github/astroport/astroport-maxence/adventure/infra/maxence.lancosme@ynov.com/nextcloud/custom_apps:/var/www/html/custom_apps
    depends_on:
      - nextcloud
